### ISSUE TITLE
finalizar TCC

### ISSUE THREAD

**Issue by hjudiss** [EASY-SPARC/TCC-Glauber#2]
- [x] substituir plots
- [x] incluir plots xy
- [x] seção de discussão em resultados, cap 5

**Comment by glauberrleite** [comment]
Estou realizando algumas mudanças na equação 3.6, pois a matriz Q pode variar, ficando Q(k)

**Comment by glauberrleite** [comment]
Feito

**Comment by glauberrleite** [comment]
Falta passar o código mais atual para o repositório e adicionar os vídeos das novas simulações. Amanhã à tarde farei, já algumas alterações ficaram no meu computador do laboratório

**Comment by hjudiss** [comment]
Muito bom.
Já adicionou as figuras também?
Já versão final?

**Comment by glauberrleite** [comment]
Isso, coloquei no overleaf

**Comment by hjudiss** [comment]
revisei, basta resolver poucos comentários e fechar

**Comment by glauberrleite** [comment]
"Em que $\text{diag}: \R^n \rightarrow \R^{n \times n}$ é uma função que retorna uma matriz diagonal com elementos definidos por seus argumentos" essa parte que ficou solta, estou pensando se deveria colocar como rodapé. Acho que a função diag é bem conhecida, mas estava imaginando que alguém poderia reclamar por não ter explicação.
